const ADD_TODO = 'ADD_TODO';
const COMPLETE_TODO = 'COMPLETE_TODO';
const DELETE_TODO = 'DELETE_TODO';
const SET_TODO_TO_ACTIVE = 'SET_TODO_TO_ACTIVE';

export {
  ADD_TODO,
  COMPLETE_TODO,
  DELETE_TODO,
  SET_TODO_TO_ACTIVE,
};