const ADD_TO_LIST = 'ADD_TO_LIST';
const COMPLETE_ITEM = 'COMPLETE_ITEM';
const REMOVE_FROM_LIST = 'REMOVE_FROM_LIST';
const SET_ITEM_ACTIVE = 'SET_ITEM_ACTIVE';

export {
  ADD_TO_LIST,
  COMPLETE_ITEM,
  REMOVE_FROM_LIST,
  SET_ITEM_ACTIVE,
};